In [2]:
#import packages
import pandas as pd
import numpy as np

In [3]:
#read data
tanz = pd.read_csv("C:\\Users\\Penelope\\Documents\\Penelope Personal\\A Python\\Macro-Eyes\\Tanzania Health facilities\\Health_Facilities_2019-12-19.csv")

tanzo = pd.read_csv("C:\\Users\\Penelope\\Documents\\Penelope Personal\\A Python\\Macro-Eyes\\Tanzania Health facilities\\Health_Facilities_2019-12-19 - not set removed.csv")

In [4]:
tanz.head()

,Facility_ID,Facility Name,Ward,Village/Street,Facility Type,Operating Status,Ownership,Latitude,Longitude,Facility_Zone,...,Diagnosis_Serices,Reproductive_&_Child_Health_Care_Serices,Growth_Monitoring/Nutrition_&_Surveliance,Oral_Health_Services(Dental_Serices),ENT_Services,Sterilazation_and_Infection_Control.2,Sterilazation_and_Infection_Control.3,Support_Services,Emergency_Preparedness,Other_Services
0,108439-1,2 Crown Dental,Not set,Not set,Dispensary,Closed,Private - For Profit,NaN,NaN,Eastern Zone,...,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set
1,111824-9,361 KJ,Makongo,Mlalakuwa,Dispensary,Operating,Public - Military,NaN,NaN,Eastern Zone,...,Laboratory Lab: Parasitology,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set
2,100022-3,663 KJ,Nyamanoro,Not set,Dispensary,Closed,Public - Military,NaN,NaN,Lake Zone,...,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set
3,113180-4,A1 Eye Solutions,Maili Moja,Tangini,Clinic - Optometry Clinic,Operating,Private - For Profit,NaN,NaN,Eastern Zone,...,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Not set,Optometry services
4,112328-0,A2Z poly,Njoro,Railway,Clinic,Operating,Private - For Profit,NaN,NaN,Northern Zone,...,Laboratory Lab: Parasitology Lab: Microbiology...,Not set,Not set,Not set,ENT Services,Not set,Not set,Not set,Not set,Not set

In [5]:
fac_type = tanz["Facility Type"]
fac_type.unique()

array(['Dispensary', 'Clinic - Optometry Clinic', 'Clinic',
       'Clinic - Other Clinic',
       'Health Labs - Level IA2 (Dispensary Laboratory)',
       'Clinic - Specialized Polyclinic', 'Health Center',
       'Maternity Home', 'Clinic - Dental Clinic',
       'Maternity and Nursing Home', 'Health Labs',
       'Hospital - District Hospital', 'Clinic - Polyclinic',
       'Hospital - Referral Hospital at Zonal Level',
       'Health Labs - Level III single purpose Health Laboratory',
       'Hospital - Other Hospital',
       'Health Labs - Level IIA2 (District Laboratory)',
       'Clinic - Super specialized clinic',
       'Health Labs - Specimen collection point',
       'Clinic - Physiotherapy Clinic', 'Hospital',
       'Clinic - General Clinic', nan,
       'Hospital - Hospital at District Level', 'Clinic - Medical Clinic',
       'Clinic - Specialized clinic', 'Clinic - Diagnostic Centre',
       'Clinic - Eye Clinic', 'Hospital - Hospital at Zonal Level',
       'Hospital - Regional Referral Hospital',
       'Hospital - Referral Hospital at Regional Level',
       'Hospital - Council Designated Hospital',
       'Hospital - Hospital at Regional Level',
       'Health Labs - Level III Multipurpose Health Laboratory',
       'Health Labs - Level IA1 (Health centre Laboratory)',
       'Nursing Home',
       'Hospital - Super Specialized Hospital at National Level',
       'Clinic - Dialysis Clinic',
       'Hospital - Referral Hospital at National Level',
       'Clinic - Super specialized Polyclinic'], dtype=object)

In [7]:
tanzo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10427 entries, 0 to 10426
Data columns (total 86 columns):
Facility_ID                                  10427 non-null object
Facility Name                                10427 non-null object
Ward                                         10307 non-null object
Village/Street                               9271 non-null object
Facility Type                                10424 non-null object
Operating Status                             10425 non-null object
Ownership                                    10420 non-null object
Latitude                                     9267 non-null float64
Longitude                                    9267 non-null float64
Facility_Zone                                10345 non-null object
Facility_Region                              10344 non-null object
Facility_District                            10344 non-null object
Facility_Council                             10344 non-null object
Facility_Location                            3946 non-null object
Common_Facility_Name                         7436 non-null object
Registration_ID                              3002 non-null object
CTC_ID                                       1406 non-null object
MTUHA_Code                                   1836 non-null object
MSD_ID                                       2141 non-null object
Facility_Type                                10342 non-null object
Facility_Ownership                           10338 non-null object
Facility_Operating_Status                    10343 non-null object
Facility_Registration_Status                 9044 non-null object
Location_Description                         3946 non-null object
Waypoint_Number                              4413 non-null object
Altitude(Meters)                             6357 non-null float64
Service_Areas(Villages)                      6694 non-null object
Catchment_Population                         3685 non-null float64
Date_Opened/Inaugurated/Upgraded             5175 non-null object
Year                                         5825 non-null float64
Postal_Address                               7085 non-null object
Postal_Code                                  1244 non-null float64
Official_Phone_#                             2696 non-null object
Official_Fax_#                               724 non-null object
Official_Email                               1412 non-null object
Facility_In-Charge_Name                      7846 non-null object
Facility_In-Charge_Cadre                     7713 non-null object
Website                                      81 non-null object
Reception_Room(s)                            6247 non-null float64
Consultation_Room(s)                         7382 non-null float64
Dressing_Room(s)                             6246 non-null float64
Ward_Room(s)                                 2146 non-null float64
Injection_Room(s)                            394 non-null float64
Observation_Room(s)                          4434 non-null float64
Remarks                                      1701 non-null object
Patient_Beds                                 6302 non-null float64
Deliery_Beds                                 5691 non-null float64
Baby_Cots                                    602 non-null float64
Ambulances                                   665 non-null float64
Cars                                         742 non-null float64
Motorcycles                                  785 non-null float64
Other_Transport                              1451 non-null object
Sterilazation_and_Infection_Control          2006 non-null object
Sterilazation_and_Infection_Control.1        7575 non-null object
Means_of_Transport_to_Referral_Point         6027 non-null object
Distance_to_Referral_Point                   5569 non-null object
Challanges/Remarks_to_Referral_Point         3507 non-null object
Source_of_Energy                             7552 non-null object
Other_Source_of_Energy                       1216 non-null object
Mobile_Networks                              7298 non-null object
Other_Mobile_Networks                        1853 non-null object
Source_of_Water                              7546 non-null object
Other_Source_of_Water                        969 non-null object
Toilet_Facility                              7801 non-null object
Toilet_Remarks                               768 non-null object
Waste_Management                             7600 non-null object
Other_Waste_Management                       767 non-null object
General_Clinical_Services                    7426 non-null object
Malaria_Diagnosis_and_Treatment              7298 non-null object
TB_Diagnosis,Care_and_Treatment              2292 non-null object
Cardiouvascula_Care_and_Treatment            264 non-null object
HIV/AIDS_Prevention                          6726 non-null object
HIV/AIDS_Care_and_Treatment                  4121 non-null object
Therapeutics                                 6567 non-null object
Prosthetics_and_Medical_Devices              145 non-null object
Health_Promotion_and_Disease_Prevention      145 non-null object
Diagnosis_Serices                            3374 non-null object
Reproductive_&_Child_Health_Care_Serices     6187 non-null object
Growth_Monitoring/Nutrition_&_Surveliance    5483 non-null object
Oral_Health_Services(Dental_Serices)         981 non-null object
ENT_Services                                 221 non-null object
Sterilazation_and_Infection_Control.2        2006 non-null object
Sterilazation_and_Infection_Control.3        7575 non-null object
Support_Services                             814 non-null object
Emergency_Preparedness                       3155 non-null object
Other_Services                               392 non-null object
dtypes: float64(18), object(68)
memory usage: 6.8+ MB

In [11]:
#operating status
tanz["Operating Status"].value_counts()

Operating                                    9016
Pending Operation - Under Construction        573
Closed                                        563
Closed (Temporary)                            210
Pending Operation - Construction Complete      63
Name: Operating Status, dtype: int64

In [14]:
tanzo.shape

(10427, 86)

In [16]:
total_cells = np.product(tanzo.shape)
total_cells

896722

In [22]:
missing_cells = tanzo.isnull().sum().sum()
missing_cells

462366

In [32]:
tanzo.isnull().sum()

Facility_ID                                  0
Facility Name                                0
Ward                                       120
Village/Street                            1156
Facility Type                                3
                                         ...
Sterilazation_and_Infection_Control.2     8421
Sterilazation_and_Infection_Control.3     2852
Support_Services                          9613
Emergency_Preparedness                    7272
Other_Services                           10035
Length: 86, dtype: int64

In [33]:
tanzo.isnull().sum().tolist()

[0,
 0,
 120,
 1156,
 3,
 2,
 7,
 1160,
 1160,
 82,
 83,
 83,
 83,
 6481,
 2991,
 7425,
 9021,
 8591,
 8286,
 85,
 89,
 84,
 1383,
 6481,
 6014,
 4070,
 3733,
 6742,
 5252,
 4602,
 3342,
 9183,
 7731,
 9703,
 9015,
 2581,
 2714,
 10346,
 4180,
 3045,
 4181,
 8281,
 10033,
 5993,
 8726,
 4125,
 4736,
 9825,
 9762,
 9685,
 9642,
 8976,
 8421,
 2852,
 4400,
 4858,
 6920,
 2875,
 9211,
 3129,
 8574,
 2881,
 9458,
 2626,
 9659,
 2827,
 9660,
 3001,
 3129,
 8135,
 10163,
 3701,
 6306,
 3860,
 10282,
 10282,
 7053,
 4240,
 4944,
 9446,
 10206,
 8421,
 2852,
 9613,
 7272,
 10035]

In [ ]:
#wow so there are only two columns with no missing values

In [23]:
percent_missing = missing_cells / total_cells * 100
percent_missing

51.56179953207348

In [25]:
tanzodropped = tanzo.dropna()
tanzodropped.head()

Empty DataFrame
Columns: [Facility_ID, Facility Name, Ward, Village/Street, Facility Type, Operating Status, Ownership, Latitude, Longitude, Facility_Zone, Facility_Region, Facility_District, Facility_Council, Facility_Location, Common_Facility_Name, Registration_ID, CTC_ID, MTUHA_Code, MSD_ID, Facility_Type, Facility_Ownership, Facility_Operating_Status, Facility_Registration_Status, Location_Description, Waypoint_Number, Altitude(Meters), Service_Areas(Villages), Catchment_Population, Date_Opened/Inaugurated/Upgraded, Year, Postal_Address, Postal_Code, Official_Phone_#, Official_Fax_#, Official_Email, Facility_In-Charge_Name, Facility_In-Charge_Cadre, Website, Reception_Room(s), Consultation_Room(s), Dressing_Room(s), Ward_Room(s), Injection_Room(s), Observation_Room(s), Remarks, Patient_Beds, Deliery_Beds, Baby_Cots, Ambulances, Cars, Motorcycles, Other_Transport, Sterilazation_and_Infection_Control, Sterilazation_and_Infection_Control.1, Means_of_Transport_to_Referral_Point, Distance_to_Referral_Point, Challanges/Remarks_to_Referral_Point, Source_of_Energy, Other_Source_of_Energy, Mobile_Networks, Other_Mobile_Networks, Source_of_Water, Other_Source_of_Water, Toilet_Facility, Toilet_Remarks, Waste_Management, Other_Waste_Management, General_Clinical_Services, Malaria_Diagnosis_and_Treatment, TB_Diagnosis,Care_and_Treatment, Cardiouvascula_Care_and_Treatment, HIV/AIDS_Prevention, HIV/AIDS_Care_and_Treatment, Therapeutics, Prosthetics_and_Medical_Devices, Health_Promotion_and_Disease_Prevention, Diagnosis_Serices, Reproductive_&_Child_Health_Care_Serices, Growth_Monitoring/Nutrition_&_Surveliance, Oral_Health_Services(Dental_Serices), ENT_Services, Sterilazation_and_Infection_Control.2, Sterilazation_and_Infection_Control.3, Support_Services, Emergency_Preparedness, Other_Services]
Index: []

[0 rows x 86 columns]

In [27]:
tanzo_col_dropped = tanzo.dropna(axis=1)
tanzo_col_dropped

      Facility_ID     Facility Name
0        108439-1    2 Crown Dental
1        111824-9            361 KJ
2        100022-3            663 KJ
3        113180-4  A1 Eye Solutions
4        112328-0          A2Z poly
...           ...               ...
10422    106570-5      ZRTC Kikombo
10423    108429-2         Zugimlole
10424    111940-3              Zulu
10425    108430-0           Zunzuli
10426    108431-8              Zuzu

[10427 rows x 2 columns]

In [28]:
#so we can't drop missing values!